### ISSUE TITLE
Org-Mode Sub-Items Not Indented Consistently in Variable Pitch Mode

### ISSUE THREAD

**Issue by stevemolitor** [protesilaos/ef-themes#9]
With `org-indent-mode` on and when using `variable-pitch-mode`, sub headings and sub-lists are not indented consistently. Here is a gif using `ef-winter`:

![](https://cdn.zappy.app/f996e271f6499307316a7b3f2428c145.png)

Note that "text" and "* Three" are not indented to the same level for example. Here is the same file using `modus-vivendi`:

![](https://cdn.zappy.app/7494d25959521714fc0a1753846c8b0f.png)

Note that everything lines up in vivendi, but not in ef-winter.

I tried with `ef-themes-variable-pitch-ui` set to `t` and `nil`, same effect.

Thanks for the great themes btw!

**Comment by protesilaos** [comment]
Thank you @stevemolitor!

I just pushed the change:

```
  commit c68c71957619c140b8115a1a814f4d764b9246ee
  Author: Protesilaos Stavrou <info@protesilaos.com>
  Date:   Thu Aug 25 22:25:10 2022 +0300
  
      Make 'org-indent' always monospaced
      
      This is essential for 'org-indent-mode' to align entries correctly.
      
      Thanks to Steve Molitor for reporting the issue 9 over at the GitHub
      mirror: <https://github.com/protesilaos/ef-themes/issues/9>.  Steven
      tested a sample file with 'modus-vivendi' and got the desired results.
      It reminded me how I handle this face with the 'modus-themes'.
  
   README.org   | 3 ++-
   ef-themes.el | 2 +-
   2 files changed, 3 insertions(+), 2 deletions(-)
```

> Thanks for the great themes btw!

You are welcome!

* * *

Are you using the package from GNU ELPA?  I plan to release version 0.4.0 in the coming days.  Maybe the beginning of next week.  This commit will be part of that version.

**Comment by stevemolitor** [comment]
@protesilaos Wow that was quick! No I cloned the repo. Will it be available via `straight` eventually?

 I can confirm it works great now, everything is all lined up:

![](https://cdn.zappy.app/195e412083e20607142d7068630e930e.png)

Thanks a bunch!

**Comment by protesilaos** [comment]
Yes, it is available right now if you are using `straight`.

> Thanks a bunch!

You are welcome!

Closing this now.

**Comment by protesilaos** [comment]
Hi @rrix and thanks for reporting this!  Does your `fixed-pitch` face have an explicit foreground?  What does the Help buffer say when you do `M-x describe-face` and search for `fixed-pitch`?

**Comment by protesilaos** [comment]
@rrix Inheriting the `default` is a problem here because that means it takes the default foreground as well.  For reference, this is `fixed-pitch` in an `emacs -Q` session:

```
Face: fixed-pitch (sample) (customize this face)

Documentation:
The basic fixed-pitch face.

Defined in ‘faces.el’.


           Family: Monospace
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified
```

When an attribute's value is `unspecified` it is taken from the closest relevant context, ultimately falling back to `default`.

Try to decouple `fixed-pitch` from `default` by not inheriting the latter.  Simply specify the `:family` of `fixed-pitch` and the rest will be done automatically.
